### ISSUE TITLE
KubeLB CLI for non-kubernetes usage

### ISSUE THREAD

**Issue by ahmedwaleedmalik** [kubermatic/kubelb#11]
**User Story**
As a KubeLB user/admin, I'd like to utilize KubeLB to provide LoadBalancers L4/L7 outside of Kubernetes as well.

**Solution details**
Introduce KubeLB CLI, which can take YAML as input and create the required configurations on the management cluster. For now, this will only support L4 load balancing.

For example, create an LB like the following, 

loadbalancer.yaml
```yaml
apiVersion: kubelb.k8c.io/v1alpha1
kind: LoadBalancer
metadata:
  name: loadbalancer
spec:
  endpoints:
    - addresses:
        - ip: 168.119.189.211
        - ip: 168.119.185.115
      ports:
        - name: a-port
          port: 32019
          protocol: TCP
  ports:
    - name: a-port
      port: 8080
      protocol: TCP
```

In the CLI, `kubelb create --lb loadbalancer.yaml --management-cluster ${path-to-kubeconfig-for-management-cluster}`. This should result in the creation of an LB, and CLI should wait for the status to be populated to output the LB IP to the user.

**Acceptance criteria**

- [ ] Introduce KubeLB CLI 
- [ ] Ensure that it's compliant with multiple architectures
- [ ] Documentation
